#!/bin/bash

##############################################################################
# Copyright 2014 Joseph Chilcote
# 
#  Licensed under the Apache License, Version 2.0 (the "License"); you may not
#  use this file except in compliance with the License. You may obtain a copy
#  of the License at
# 
#       http://www.apache.org/licenses/LICENSE-2.0
# 
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations
#  under the License.
##############################################################################

set -x
if [ -e /usr/local/bin/edify ]; then
    rm /usr/local/bin/edify
fi
ln -s $(pwd)/edify /usr/local/bin/edify

if [ ! -d /usr/local/share/edify ]; then
	/bin/mkdir -p /usr/local/share/edify
fi

if [ -L /usr/local/share/edify/com.github.edify.plist ]; then
    rm /usr/local/share/edify/com.github.edify.plist
fi
ln -s $(pwd)/com.github.edify.plist /usr/local/share/edify/com.github.edify.plist
